import { describe, it, expect } from 'vitest';
import {
  renderTemplate,
  sanitizeTemplateValue,
  getCommentStyle,
  getGeneratedHeader,
  mergePermissions,
  insertHeader,
} from '../sync.mjs';

// ---------------------------------------------------------------------------
// renderTemplate
// ---------------------------------------------------------------------------
describe('renderTemplate', () => {
  it('replaces simple placeholders', () => {
    const result = renderTemplate('Hello {{name}}!', { name: 'World' });
    expect(result).toBe('Hello World!');
  });

  it('replaces multiple placeholders', () => {
    const result = renderTemplate('{{a}} and {{b}}', { a: '1', b: '2' });
    expect(result).toBe('1 and 2');
  });

  it('replaces longest keys first to prevent partial collisions', () => {
    const result = renderTemplate('{{version}} {{versionInfo}}', {
      version: '1.0',
      versionInfo: 'v1.0-beta',
    });
    expect(result).toBe('1.0 v1.0-beta');
  });

  it('serialises non-string values as JSON', () => {
    const result = renderTemplate('items: {{list}}', { list: ['a', 'b'] });
    expect(result).toBe('items: ["a","b"]');
  });

  it('leaves unresolved placeholders intact', () => {
    const result = renderTemplate('{{known}} {{unknown}}', { known: 'yes' });
    expect(result).toContain('{{unknown}}');
  });

  it('handles empty vars object', () => {
    const result = renderTemplate('no vars here', {});
    expect(result).toBe('no vars here');
  });

  it('handles empty template', () => {
    const result = renderTemplate('', { key: 'value' });
    expect(result).toBe('');
  });
});

// ---------------------------------------------------------------------------
// sanitizeTemplateValue
// ---------------------------------------------------------------------------
describe('sanitizeTemplateValue', () => {
  it('preserves safe characters', () => {
    expect(sanitizeTemplateValue('my-project_v2.0')).toBe('my-project_v2.0');
  });

  it('strips shell injection characters', () => {
    expect(sanitizeTemplateValue('$(rm -rf /)')).toBe('rm -rf /');
  });

  it('strips backtick injection', () => {
    expect(sanitizeTemplateValue('`whoami`')).toBe('whoami');
  });

  it('strips pipe and semicolons', () => {
    expect(sanitizeTemplateValue('name; echo pwned | cat')).toBe('name echo pwned  cat');
  });

  it('preserves spaces, slashes, and @ symbols', () => {
    expect(sanitizeTemplateValue('user@example.com /home/user')).toBe('user@example.com /home/user');
  });
});

// ---------------------------------------------------------------------------
// getCommentStyle
// ---------------------------------------------------------------------------
describe('getCommentStyle', () => {
  it('returns HTML comments for .md', () => {
    expect(getCommentStyle('.md')).toEqual({ start: '<!--', end: '-->' });
  });

  it('returns HTML comments for .mdc', () => {
    expect(getCommentStyle('.mdc')).toEqual({ start: '<!--', end: '-->' });
  });

  it('returns null for .json', () => {
    expect(getCommentStyle('.json')).toBeNull();
  });

  it('returns hash comments for .yaml', () => {
    expect(getCommentStyle('.yaml')).toEqual({ start: '#', end: '' });
  });

  it('returns hash comments for .sh', () => {
    expect(getCommentStyle('.sh')).toEqual({ start: '#', end: '' });
  });

  it('returns hash comments for unknown extensions', () => {
    expect(getCommentStyle('.xyz')).toEqual({ start: '#', end: '' });
  });
});

// ---------------------------------------------------------------------------
// getGeneratedHeader
// ---------------------------------------------------------------------------
describe('getGeneratedHeader', () => {
  it('generates a markdown header', () => {
    const header = getGeneratedHeader('0.1.0', 'my-repo', '.md');
    expect(header).toContain('GENERATED by AgentKit Forge v0.1.0');
    expect(header).toContain('agentkit/overlays/my-repo');
    expect(header).toContain('pnpm -C agentkit agentkit:sync');
  });

  it('returns empty string for JSON', () => {
    expect(getGeneratedHeader('0.1.0', 'my-repo', '.json')).toBe('');
  });

  it('generates YAML-style header for .yml', () => {
    const header = getGeneratedHeader('0.1.0', 'my-repo', '.yml');
    expect(header).toContain('# GENERATED by AgentKit Forge v0.1.0');
  });
});

// ---------------------------------------------------------------------------
// mergePermissions
// ---------------------------------------------------------------------------
describe('mergePermissions', () => {
  it('merges allow lists with deduplication', () => {
    const result = mergePermissions(
      { allow: ['Read', 'Write'] },
      { allow: ['Write', 'Bash'] }
    );
    expect(result.allow).toEqual(['Read', 'Write', 'Bash']);
  });

  it('merges deny lists with deduplication', () => {
    const result = mergePermissions(
      { deny: ['Bash'] },
      { deny: ['Bash', 'Write'] }
    );
    expect(result.deny).toEqual(['Bash', 'Write']);
  });

  it('handles empty base', () => {
    const result = mergePermissions({}, { allow: ['Read'], deny: ['Bash'] });
    expect(result.allow).toEqual(['Read']);
    expect(result.deny).toEqual(['Bash']);
  });

  it('handles empty overlay', () => {
    const result = mergePermissions({ allow: ['Read'], deny: ['Bash'] }, {});
    expect(result.allow).toEqual(['Read']);
    expect(result.deny).toEqual(['Bash']);
  });

  it('handles both empty', () => {
    const result = mergePermissions({}, {});
    expect(result.allow).toEqual([]);
    expect(result.deny).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// insertHeader
// ---------------------------------------------------------------------------
describe('insertHeader', () => {
  it('prepends header to plain content', () => {
    const result = insertHeader('Hello world', '.yml', '0.1.0', 'test');
    expect(result).toMatch(/^# GENERATED by AgentKit Forge/);
    expect(result).toContain('Hello world');
  });

  it('skips if header already present', () => {
    const content = '# GENERATED by AgentKit Forge v0.1.0\nHello';
    const result = insertHeader(content, '.yml', '0.1.0', 'test');
    expect(result).toBe(content);
  });

  it('inserts after shebang in .sh files', () => {
    const content = '#!/usr/bin/env bash\necho "hello"';
    const result = insertHeader(content, '.sh', '0.1.0', 'test');
    expect(result).toMatch(/^#!\/usr\/bin\/env bash\n# GENERATED/);
    expect(result).toContain('echo "hello"');
  });

  it('inserts after frontmatter in .md files', () => {
    const content = '---\ntitle: Test\n---\n# Content';
    const result = insertHeader(content, '.md', '0.1.0', 'test');
    expect(result).toContain('title: Test');
    expect(result).toContain('GENERATED by AgentKit Forge');
    expect(result).toContain('# Content');
  });

  it('returns content unchanged for .json', () => {
    const content = '{"key": "value"}';
    const result = insertHeader(content, '.json', '0.1.0', 'test');
    expect(result).toBe(content);
  });
});
